name: Jetty Run

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_APISERVER_REPO: dependencytrack/apiserver
      DOCKER_BUNDLED_REPO: dependencytrack/bundled
      DOCKER_TAG: snapshot

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Run with Maven
      run: |-
        mvn clean
        mvn package -Dmaven.test.skip=true -P clean-exclude-wars -P embedded-jetty -Dlogback.configuration.file=src/main/docker/logback.xml
        mvn clean -P clean-exclude-wars
        mvn package -Dmaven.test.skip=true -P embedded-jetty -P bundle-ui -Dlogback.configuration.file=src/main/docker/logback.xml
        mvn clean -P clean-exclude-wars
        mvn -P enhance jetty:run

















